### PR TITLE
Return TestResult from plugin execution

### LINKED ISSUE #38: Implement logic of plugin execution results aggregation
The framework should somehow keep track of the number of successful and failing tests, maybe debug info about execution time etc. It should probably be returned from `Save.performAnalysis`

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Added classes
* Update Plugin API
* Updated FixPlugin

Closes #38

### CODE REVIEW

File: save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt [hunk 1]
```diff
@@ -18,22 +24,37 @@ import okio.Path.Companion.toPath
...
+        return sequence {
+            files.forEach { (expected, test) ->
                 pb.exec(fixPluginConfig.execCmd.split(" "), null)
                 val fixedLines = FileSystem.SYSTEM.readLines(
                     if (fixPluginConfig.inPlace) test else test.parent!! / fixPluginConfig.destinationFileFor(test).toPath()
                 )
                 val expectedLines = FileSystem.SYSTEM.readLines(expected)
-                // todo: check equality here
-                diff(expectedLines, fixedLines)
+                val status = diff(expectedLines, fixedLines).let { patch ->
```
Comment (kgevorkyan) [inline save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt:48]: Maybe we can add some debug output about execution results?

Comment (petertrr) [reply save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt:48]: Yeah, that's a good idea. We can have a new field `debugInfo` in `TestResult`, and it can contain execution time, or `execCmd`'s stdout and stderr

File: save-core/src/commonMain/kotlin/org/cqfn/save/core/Save.kt [hunk 2]
```diff
@@ -24,10 +32,24 @@ class Save(
...
+    @Suppress("WHEN_WITHOUT_ELSE")  // TestResult is a sealed class
+    private fun handleResult(testResult: TestResult) {
+        when (testResult.status) {
+            is Success -> logDebug("Test on resources [${testResult.resources}] has completed successfully")
+            is Failure -> logWarn("Test on resources [${testResult.resources}] has failed: ${testResult.status.reason}")
+            is Ignored -> logWarn("Test on resources [${testResult.resources}] has been ignored: ${testResult.status.reason}")
+            is Crash -> logError("Test on resources [${testResult.resources}] has crashed: ${testResult.status.throwable.message}." +
+                    "Please report an issue at https://github.com/cqfn/save")
+        }
+        if (saveProperties.debug == true) {
```
[the remark this answers is not in the document]
Comment (petertrr) [reply save-core/src/commonMain/kotlin/org/cqfn/save/core/Save.kt:51]: Yes, makes sense. Also, we should probably change `logDebug` to accept lazy messages in future (like `fun logDebug(() -> String)` so that the strings are created only when needed.

File: save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt [hunk 3]
```diff
@@ -18,22 +25,41 @@ import okio.Path.Companion.toPath
...
+                    if (patch.deltas.isEmpty()) {
+                        Success
+                    } else {
+                        Failure(patch.formatToString())
+                    }
+                }
+                yield(TestResult(
+                    listOf(expected, test),
+                    status,
+                    DebugInfo(executionResult.stdout.joinToString("\n"), null)
```
Comment (kgevorkyan) [inline save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt:59]: What about `executionResult.stderr`?

Comment (petertrr) [reply save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt:59]: Added

Comment (petertrr) [reply save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt:59]: Added

**Review by kgevorkyan — APPROVED** [review]
lgtm

File: save-core/src/commonMain/kotlin/org/cqfn/save/core/result/TestStatus.kt [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+ */
+
+package org.cqfn.save.core.result
+
+/**
+ * Base class for final statuses of test execution
+ */
+sealed class TestStatus
+
+object Success : TestStatus()
```
Comment (akuleshov7) [inline save-core/src/commonMain/kotlin/org/cqfn/save/core/result/TestStatus.kt:12]: please rename to PASS

File: save-core/src/commonMain/kotlin/org/cqfn/save/core/result/TestStatus.kt [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+
+/**
+ * @property reason reason of failure
+ */
+data class Failure(val reason: String) : TestStatus()
```
Comment (akuleshov7) [inline save-core/src/commonMain/kotlin/org/cqfn/save/core/result/TestStatus.kt:17]: Please rename to FAIL

**Review by akuleshov7 — APPROVED** [review]
lgtm
