### PR TITLE
Make 'defaultResourceNamePattern' configurable for both Warn and Fix plugins

### LINKED ISSUE #105: Make 'defaultResourceNamePattern' configurable for both Warn and Fix plugins
In Plugins we have the following constants: 
```
    companion object {
        internal val defaultResourceNamePattern = Regex("""(.+)(Expected|Test)\.[\w\d]+""")
    }

and 

    internal val defaultResourceNamePattern = Regex("""(.+)Test\.[\w\d]+""")
```

Please check the logic and add hardcodes in **one and only place**.

### PR DESCRIPTION
**Pull request by Cheshiriks**
Make 'defaultResourceNamePattern' configurable for both Warn and Fix plugins

### What's done:
* Added warn and fix config - resourceNamePattern

Closes #105

### CODE REVIEW

File: save-common/src/commonMain/kotlin/org/cqfn/save/core/plugin/Plugin.kt [hunk 1]
```diff
@@ -18,9 +18,9 @@ abstract class Plugin(open val testConfig: TestConfig, private val testFiles: Li
      *
      * @return a sequence of [TestResult]s for each group of test resources
      */
-    fun execute(): Sequence<TestResult> = handleFiles(
+    open fun execute(): Sequence<TestResult> = handleFiles(
```
Comment (petertrr) [inline save-common/src/commonMain/kotlin/org/cqfn/save/core/plugin/Plugin.kt:21]: Between making this method open and override it in every plugin and not passing `regex` via argument into `rawDiscoverTestFiles`, I'd choose the latter. You can take regex from plugin config in every plugin.

File: save-common/src/commonMain/kotlin/org/cqfn/save/core/plugin/Plugin.kt [hunk 2]
```diff
@@ -54,9 +55,10 @@ abstract class Plugin(open val testConfig: TestConfig, private val testFiles: Li
      * Discover groups of resource files which will be used to run tests.
      *
      * @param resourceDirectories a sequence of [Path]s, which contain this plugin's resources
+     * @param regex default regex for actual warnings in the tool output
```
Comment (petertrr) [inline save-common/src/commonMain/kotlin/org/cqfn/save/core/plugin/Plugin.kt:58]: That's not correct

File: save-plugins/fix-plugin/README.md [hunk 3]
```diff
@@ -46,9 +46,11 @@ exec_cmd="./ktlint -R diktat-0.4.2.jar -F"
 testFilePattern="*Test.kt"
 expectedFilePattern="*Expected.kt"
 batchMode = false
+resourceNamePattern = """(.+)(Expected|Test)\.[\w\d]+"""
```
Comment (petertrr) [inline save-plugins/fix-plugin/README.md:49]: Please check correct toml syntax for this; what's the difference between usual and triple-quoted string and whether slashes need escaping

File: save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPluginConfig.kt [hunk 4]
```diff
@@ -51,3 +65,16 @@ data class FixPluginConfig(
         internal val defaultResourceNamePattern = Regex("""(.+)(Expected|Test)\.[\w\d]+""")
     }
 }
+
+@OptIn(ExperimentalSerializationApi::class)
+@Serializer(forClass = Regex::class)
+object RegexSerializer : KSerializer<Regex> {
```
Comment (petertrr) [inline save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPluginConfig.kt:71]: Let's move it to `save-common`, because it's now duplicated in two places already

File: save-plugins/warn-plugin/README.md [hunk 5]
```diff
@@ -67,6 +67,7 @@ columnCaptureGroup = 2  # index of regex capture group for column number, used w
 messageCaptureGroup = 3  # index of regex capture group for message text
 warningTextHasColumn = true
 warningTextHasLine = true
+resourceNamePattern = """(.+)Test\.[\w\d]+"""
```
Comment (petertrr) [inline save-plugins/warn-plugin/README.md:70]: Same here, check toml syntax

**Review by petertrr — CHANGES_REQUESTED** [review]

File: save-plugins/warn-plugin/src/commonMain/kotlin/org/cqfn/save/plugin/warn/WarnPlugin.kt [hunk 6]
```diff
@@ -37,12 +37,16 @@ class WarnPlugin(testConfig: TestConfig, testFiles: List<String> = emptyList())
...
-                .filter { defaultResourceNamePattern.matches(it.name) }
-        }
-        .filter { it.isNotEmpty() }
+    override fun rawDiscoverTestFiles(resourceDirectories: Sequence<Path>): Sequence<List<Path>> {
+        val warnPluginConfig = testConfig.pluginConfigs.filterIsInstance<WarnPluginConfig>().single()
+        val regex = warnPluginConfig.resourceNamePattern ?: defaultResourceNamePattern
+        return resourceDirectories
+            .map { directory ->
+                FileSystem.SYSTEM.list(directory)
+                    .filter { (regex ?: defaultResourceNamePattern).matches(it.name) }
```
Comment (kgevorkyan) [inline save-plugins/warn-plugin/src/commonMain/kotlin/org/cqfn/save/plugin/warn/WarnPlugin.kt:46]: It will always match `regex`
```suggestion
                    .filter { (regex).matches(it.name) }
```

Comment (Cheshiriks) [reply save-plugins/warn-plugin/src/commonMain/kotlin/org/cqfn/save/plugin/warn/WarnPlugin.kt]: fixed:)

File: save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt [hunk 7]
```diff
@@ -61,24 +61,28 @@ class FixPlugin(testConfig: TestConfig, testFiles: List<String> = emptyList()) :
...
+                    matchResult?.groupValues?.get(1)  // this is a capture group for the start of file name
                 }
-                .values
-        }
-        .filter { it.isNotEmpty() }
+                    .filter { it.value.size > 1 && it.key != null }
+                    .mapValues { (name, group) ->
+                        require(group.size == 2) { "Files should be grouped in pairs, but for name $name these files have been discovered: $group" }
+                        listOf(
+                            group.first { it.name.contains("Expected.") },
```
Comment (akuleshov7) [inline save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt:78]: why is it still here hardcoded?

File: save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPluginConfig.kt [hunk 8]
```diff
@@ -13,11 +18,13 @@ import kotlinx.serialization.Serializable
  *
  * @property execCmd a command that will be executed to mutate test file contents
  * @property destinationFileSuffix [execCmd] should append this suffix to the file name after mutating it.
+ * @property resourceNamePattern regex for the name of the test files
  */
 @Serializable
 data class FixPluginConfig(
     val execCmd: String,
     val destinationFileSuffix: String? = null,
+    val resourceNamePattern: Regex? = null
```
Comment (akuleshov7) [inline save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPluginConfig.kt:27]: wtf is that? 
We should have simple thing for resources: `destinationFileSuffix` and `testFileSuffix`

**Review by akuleshov7 — CHANGES_REQUESTED** [review]
please fix issues

File: save-common/src/commonMain/kotlin/org/cqfn/save/core/plugin/Plugin.kt [hunk 9]
```diff
@@ -58,6 +61,11 @@ abstract class Plugin(open val testConfig: TestConfig, private val testFiles: Li
      */
     abstract fun rawDiscoverTestFiles(resourceDirectories: Sequence<Path>): Sequence<List<Path>>
 
+    /**
+     * Method for cleaning up a directory.
+     */
+    abstract fun cleanDir()
```
Comment (akuleshov7) [inline save-common/src/commonMain/kotlin/org/cqfn/save/core/plugin/Plugin.kt:67]: please rename it to something more informative, like cleanupTempDir

File: save-common/src/commonMain/kotlin/org/cqfn/save/core/plugin/PluginConfig.kt [hunk 10]
```diff
@@ -69,3 +77,16 @@ data class GeneralConfig(
         )
     }
 }
+
+@OptIn(ExperimentalSerializationApi::class)
```
Comment (akuleshov7) [inline save-common/src/commonMain/kotlin/org/cqfn/save/core/plugin/PluginConfig.kt:81]: CustomSerializer file

File: save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt [hunk 11]
```diff
@@ -67,24 +67,54 @@ class FixPlugin(testConfig: TestConfig, testFiles: List<String> = emptyList()) :
...
-        .map { FileSystem.SYSTEM.list(it) }
-        .flatMap { files ->
-            files.groupBy {
-                val matchResult = defaultResourceNamePattern.matchEntire(it.name)
-                matchResult?.groupValues?.get(1)  // this is a capture group for the start of file name
+    private fun createTestFile(path: Path): Path {
+        val tmpDir = (FileSystem.SYSTEM_TEMPORARY_DIRECTORY / FixPlugin::class.simpleName!!)
+
+        if (!fs.exists(tmpDir)) {
+            fs.createDirectory(tmpDir)
```
Comment (akuleshov7) [inline save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt:74]: please handle exception and do logErrorAndExit

File: save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt [hunk 12]
```diff
@@ -67,24 +67,54 @@ class FixPlugin(testConfig: TestConfig, testFiles: List<String> = emptyList()) :
...
+        }
+        val pathCopy: Path = tmpDir / path.name
+        fs.write(fs.createFile(pathCopy)) {
```
Comment (akuleshov7) [inline save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt:77]: do not copy line by line 
```
try (Source a = Okio.source(from); BufferedSink b = Okio.buffer(Okio.sink(to))) {
  b.writeAll(a);
```
}

File: save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt [hunk 13]
```diff
@@ -67,24 +67,54 @@ class FixPlugin(testConfig: TestConfig, testFiles: List<String> = emptyList()) :
...
+                            group.first { it.name.contains("$resourceNameTest.") }
+                        )
+                    }
+                    .values
+            }
+            .filter { it.isNotEmpty() }
+    }
+
+    override fun cleanDir() {
+        val tmpDir = (FileSystem.SYSTEM_TEMPORARY_DIRECTORY / FixPlugin::class.simpleName!!)
```
Comment (akuleshov7) [inline save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt:113]: handle exceptions

File: save-plugins/warn-plugin/src/commonMain/kotlin/org/cqfn/save/plugin/warn/WarnPlugin.kt [hunk 14]
```diff
@@ -47,12 +46,23 @@ class WarnPlugin(testConfig: TestConfig, testFiles: List<String> = emptyList())
...
+        return resourceDirectories
+            .map { directory ->
+                FileSystem.SYSTEM.list(directory)
+                    .filter { (regex).matches(it.name) }
+            }
+            .filter { it.isNotEmpty() }
+    }
+
+    override fun cleanDir() {
+        val tmpDir = (FileSystem.SYSTEM_TEMPORARY_DIRECTORY / WarnPlugin::class.simpleName!!)
```
Comment (akuleshov7) [inline save-plugins/warn-plugin/src/commonMain/kotlin/org/cqfn/save/plugin/warn/WarnPlugin.kt:61]: exceptions, as always (you can do it in parent)

**Review by akuleshov7 — CHANGES_REQUESTED** [review]
pls refactor plguin part

File: save-common/src/commonMain/kotlin/org/cqfn/save/core/files/FileUtils.kt [hunk 15]
```diff
@@ -98,6 +98,14 @@ fun FileSystem.readLines(path: Path): List<String> = this.read(path) {
     generateSequence { readUtf8Line() }.toList()
 }
 
+/**
+ * @param path a path to a file
+ * @return string from the file
+ */
+fun FileSystem.readFile(path: Path): String = this.read(path) {
```
Comment (petertrr) [inline save-common/src/commonMain/kotlin/org/cqfn/save/core/files/FileUtils.kt:105]: How is this different from `readLines`?

File: save-common/src/commonMain/kotlin/org/cqfn/save/core/plugin/Plugin.kt [hunk 16]
```diff
@@ -58,6 +63,48 @@ abstract class Plugin(open val testConfig: TestConfig, private val testFiles: Li
...
+     */
+    @Suppress(
+        "TooGenericExceptionCaught",
+        "SwallowedException"
+    )
+    private fun clean() {
+        try {
+            cleanupTempDir()
+        } catch (e: Exception) {
+            throw TempDirException("\"Could not delete temp dir, cause: ${e.message}\"")
```
Comment (petertrr) [inline save-common/src/commonMain/kotlin/org/cqfn/save/core/plugin/Plugin.kt:84]: Why additional quotes?

File: save-common/src/commonMain/kotlin/org/cqfn/save/core/plugin/Plugin.kt [hunk 17]
```diff
@@ -58,6 +63,48 @@ abstract class Plugin(open val testConfig: TestConfig, private val testFiles: Li
...
+    abstract fun cleanupTempDir()
+
+    /**
+     * Method for call cleanupTempDir().
+     *
+     * @throws TempDirException when deleting temp dir
+     */
+    @Suppress(
+        "TooGenericExceptionCaught",
+        "SwallowedException"
```
Comment (petertrr) [inline save-common/src/commonMain/kotlin/org/cqfn/save/core/plugin/Plugin.kt:78]: I think re-throwing isn't detected by this inspection, is it?

File: save-common/src/commonMain/kotlin/org/cqfn/save/core/utils/CustomSerializer.kt [hunk 18]
```diff
@@ -0,0 +1,30 @@
...
+import kotlinx.serialization.descriptors.PrimitiveKind
+import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
+import kotlinx.serialization.descriptors.SerialDescriptor
+import kotlinx.serialization.encoding.Decoder
+import kotlinx.serialization.encoding.Encoder
+
+/**
+ * Class for custom serializer
+ */
+class CustomSerializer
```
Comment (petertrr) [inline save-common/src/commonMain/kotlin/org/cqfn/save/core/utils/CustomSerializer.kt:17]: empty class?

File: save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPluginConfig.kt [hunk 19]
```diff
@@ -1,49 +1,64 @@
+@file:Suppress("HEADER_MISSING_IN_NON_SINGLE_CLASS_FILE")
```
Comment (petertrr) [inline save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPluginConfig.kt:1]: I think there is a single class here?

File: save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPluginConfig.kt [hunk 20]
```diff
@@ -1,49 +1,64 @@
...
-     *
-     * @param original an original file
-     * @return a name of destination file
-     */
-    fun destinationFileFor(original: Path): String {
-        requireNotNull(destinationFileSuffix) { "This method should never be called when destinationFileSuffix is null" }
-        return original.name.run {
-            substringBeforeLast(".") + destinationFileSuffix + "." + substringAfterLast(".")
+    private fun resourceNamePattern(): Regex {
+        val isNotNullResourceNameTestSuffix = resourceNameTestSuffix != null
```
Comment (petertrr) [inline save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPluginConfig.kt:55]: Can you use `resourceNameTest` here, instead of checking nullability once again?

File: save-plugins/warn-plugin/src/commonMain/kotlin/org/cqfn/save/plugin/warn/WarnPluginConfig.kt [hunk 21]
```diff
@@ -60,10 +60,18 @@ data class WarnPluginConfig(
...
+            this.testNameSuffix ?: other.testNameSuffix
         )
     }
 
+    private fun resourceNamePattern(): Regex = testNameSuffix?.let {
+        Regex("""(.+)$testNameSuffix\.[\w\d]+""")
+    }
+        ?: run {
+            Regex("""(.+)Test\.[\w\d]+""")
+        }
```
Comment (petertrr) [inline save-plugins/warn-plugin/src/commonMain/kotlin/org/cqfn/save/plugin/warn/WarnPluginConfig.kt:73]:
```suggestion
    private fun resourceNamePattern(): Regex = (testNameSuffix ?: "Test").let {
        Regex("""(.+)$it\.[\w\d]+""")
    }
```
I'd write like this, in order not to repeat regex twice

**Review by petertrr — CHANGES_REQUESTED** [review]

File: save-common/src/commonMain/kotlin/org/cqfn/save/core/files/FileUtils.kt (hunk 15 above)
Comment (Cheshiriks) [reply save-common/src/commonMain/kotlin/org/cqfn/save/core/files/FileUtils.kt:105]: returns the entire file as one line

Comment (petertrr) [reply save-common/src/commonMain/kotlin/org/cqfn/save/core/files/FileUtils.kt:105]: Why not just `readLines().joinToString("\n")` then?

Comment (Cheshiriks) [reply save-common/src/commonMain/kotlin/org/cqfn/save/core/files/FileUtils.kt:105]: Wouldn't that be an extra action?
We read the file line by line first. Then we make a list of string, and then glue it again into a one string.

Comment (petertrr) [reply save-common/src/commonMain/kotlin/org/cqfn/save/core/files/FileUtils.kt:105]: yeah, ok

**Review by petertrr — APPROVED** [review]
looks ok to me, please check Andrey's suggestion about `writeAll`

File: save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt (hunk 11 above)
Comment (Cheshiriks) [reply save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt]: Created TempDirException for this

File: save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt (hunk 12 above)
Comment (Cheshiriks) [reply save-plugins/fix-plugin/src/commonMain/kotlin/org/cqfn/save/plugins/fix/FixPlugin.kt:75]: fixed

**Review by akuleshov7 — APPROVED** [review]
