### PR TITLE
Bugfix: run individual tests and individual test suites

### LINKED ISSUE #152: Execution of individual tests is broken
`./save  warn/chapter1/save.toml` - is broken
`./save EnumValueSnakeCaseTest.kt` - is broken

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Changed logic

We have introduced a regression at some point, that both these modes have stopped working. This PR re-introduces this logic.

#### TODO:
* add tests - can be done under #155 

Closes #152

### CODE REVIEW

File: save-common/src/commonMain/kotlin/org/cqfn/save/core/config/TestConfig.kt [hunk 1]
```diff
@@ -67,13 +69,30 @@ data class TestConfig(
...
-        return listOf(this) + this.childConfigs.flatMap { it.getAllTestConfigs() }
-    }
+    fun getAllTestConfigsForFiles(requestedConfigs: List<String>): List<TestConfig> =
+            if (requestedConfigs.isEmpty()) {
+                getAllTestConfigs()
+            } else {
+                getAllTestConfigs().filter { testConfig ->
+                    requestedConfigs.any {
+                        // `testConfig`'s directory is a parent of `requestedConfig`'s directory
+                        testConfig.directory in it.toPath().parents() ||
```
Comment (akuleshov7) [inline save-common/src/commonMain/kotlin/org/cqfn/save/core/config/TestConfig.kt:90]: `it.toPath().parents()` move to variable? ot may be not

**Review by akuleshov7 — APPROVED** [review]
