### PR TITLE
Calculate number of tests in PlainTextReporter

### LINKED ISSUE #251: Calculation of a pass-rate
Save is now simply printing test results, but no information about the pass-rate and numbers of passed and failed tests.
Need to print this statistics, that would be useful.

### PR DESCRIPTION
**Pull request by petertrr**
### What's done:
* Added Statistics.kt
* Use it in PlainTextReporter.kt

Closes #251

Now last lines of SAVE's output look like this:
```
| Chapter3 | WarnPlugin | warn-dir\chapter3\GenericFunctionTest.kt | Pass |  |
--------------------------------
SUCCESS: 9 tests, 100% successful, failed: 0, skipped: 0
[INFO]: SAVE has finished execution. You can rerun with --debug for additional information.
```

### CODE REVIEW

File: save-common/src/commonMain/kotlin/org/cqfn/save/core/reporter/Statistics.kt [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+    var crashed: Int = 0
+
+    /**
+     * Update fields of this class based on the received [TestResult]
+     *
+     * @param event an event to update statistics
+     */
+    @Suppress("WHEN_WITHOUT_ELSE")
+    fun updateFrom(event: TestResult) {
+        total += 1
```
Comment (kgevorkyan) [inline save-common/src/commonMain/kotlin/org/cqfn/save/core/reporter/Statistics.kt:45]: What do you think?
```suggestion
        total++
```

**Review by kgevorkyan — APPROVED** [review]

File: save-common/src/commonMain/kotlin/org/cqfn/save/core/reporter/Statistics.kt (hunk 1 above)
Comment (petertrr) [reply save-common/src/commonMain/kotlin/org/cqfn/save/core/reporter/Statistics.kt]: Yes, that's better. Changed
